name: Check README.md
on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  readme:
    name: Check README.md
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: mozilla/actions/rust@95b043d77461064eed6fbffa7b3f240bcbf19d3b # v1.1.5
        with:
          tools: cargo-rdme
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check README is up to date
        run: |
          cd mtu
          cargo rdme --check
